# Email Configuration
email.host=smtp.gmail.com
email.port=587
email.username=developerdanidu@gmail.com
email.password=ncopvrxotjlitjdh
email.from=Sunrise Dental Clinic
email.auth=true
email.starttls=true